version: '3.3'

volumes:
  v-metabase:

networks:
  luma-network:

services:
  luma-postgres:
    container_name: luma-postgres
    image: postgres:14.2
    networks:
      - luma-network
    env_file: .env
    ports:
      - '5432:5432'

  luma-adminer:
    container_name: luma-adminer
    image: adminer:latest
    ports:
      - '81:8080'
    networks:
      - luma-network
    env_file: .env
